name: CI / Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/upload-artifact@v3.1.4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B clean install

      - name: Run tests
        run: mvn test

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3.1.4
        with:
          name: test-results
          path: target/surefire-reports/

