openapi: 3.0.3
info:
  title: Event Booking API
  version: 1.0.0
  description: API for managing users, events, and bookings.

servers:
  - url: http://localhost:8080

paths:
  /api/users:
    get:
      summary: Get all users
      tags: [Users]
      responses:
        '200':
          description: A list of users
    post:
      summary: Create a new user
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created

  /api/users/{id}:
    get:
      summary: Get user by ID
      tags: [Users]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User found
        '404':
          description: User not found

  /api/events:
    get:
      summary: Get all events
      tags: [Events]
      responses:
        '200':
          description: A list of events
    post:
      summary: Create a new event
      tags: [Events]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '201':
          description: Event created

  /api/events/{id}:
    get:
      summary: Get event by ID
      tags: [Events]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Event found
        '404':
          description: Event not found

  /api/bookings:
    get:
      summary: Get all bookings
      tags: [Bookings]
      responses:
        '200':
          description: A list of bookings
    post:
      summary: Book an event
      tags: [Bookings]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Booking'
      responses:
        '201':
          description: Booking created
        '400':
          description: Booking limit exceeded

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string

    Event:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        date:
          type: string
          format: date
        location:
          type: string

    Booking:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        eventId:
          type: string
